const translations = {
  de: {
    skip: "Zum Inhalt springen",
    draftLabel: "Arbeitskonzept",
    draftText: "Nicht zur Veröffentlichung · Inhalte und Nachweise werden gemeinsam geprüft",
    brandSub: "Ingenieurbüro · Immobilien und Bauprojekte",
    menu: "Menü",
    navPaths: "Ihr Vorhaben",
    navServices: "Leistungen",
    navProjects: "Projekte",
    navProfile: "Profil",
    navProcess: "Vorgehen",
    navContact: "Kontakt",
    heroEyebrow: "Berlin · Teltow · Brandenburg",
    heroTitle: "Komplexe Ingenieur\u00adleistungen für Immobilien und Bauprojekte.",
    heroLead: "Technische Prüfung, Bewertung, Planung und Bauleitung – einzeln oder als abgestimmter Weg bis zur Übergabe.",
    heroScope: "Wir prüfen, planen, koordinieren und überwachen. Die Bauausführung erfolgt durch beauftragte Fachunternehmen.",
    heroCta: "Projekt besprechen",
    heroSecondary: "Ausgewählte Projekte",
    proofSince: "Beginn der Tätigkeit im Bauwesen¹",
    proofPubs: "wissenschaftliche Arbeiten¹",
    proofPatents: "Patente im Baustoffbereich¹",
    proofNote: "¹ Angaben des bestehenden Webauftritts; Nachweise und Formulierungen werden vor Veröffentlichung bestätigt.",
    heroCaption: "Sanierung, Modernisierung und Neubau",
    pathsEyebrow: "Ein Ansprechpartner · einzelne Module oder abgestimmtes Gesamtpaket",
    pathsTitle: "Welches Vorhaben möchten Sie sicher entscheiden?",
    pathsIntro: "Der Einstieg folgt Ihrer Situation – nicht einer unübersichtlichen Liste technischer Gewerke.",
    path1Title: "Immobilie kaufen oder verkaufen",
    path1Text: "Technischen Zustand, erkennbare Risiken, Folgekosten und Marktwert getrennt und nachvollziehbar prüfen.",
    path2Title: "Bestand prüfen, sanieren oder umbauen",
    path2Text: "Schäden und Ursachen klären, Maßnahmen planen und die Ausführung fachlich begleiten.",
    path3Title: "Neu bauen – von der Planung bis zur Übergabe",
    path3Text: "Genehmigung, Ausschreibung, Vergabe, Bauleitung, Qualitätskontrolle und Abnahme als abgestimmter Prozess.",
    servicesEyebrow: "Nach Geschäftswert und realen Kundenfragen geordnet",
    servicesTitle: "Die Leistungen – einzeln wählbar, sinnvoll kombinierbar.",
    service1Title: "Bauleitung",
    service1Text: "Koordination von Fachunternehmen, Terminen, Qualität und Entscheidungen bis zur geordneten Übergabe.",
    service1Tags: "Koordination · Termine · Qualität",
    service2Title: "Bau- und Schadengutachten",
    service2Text: "Technische Untersuchung von Schäden, Mängeln und Ursachen mit nachvollziehbarer Dokumentation.",
    service2Tags: "Balkon · Dach · Keller · Abnahme",
    service3Title: "Immobilienbewertung und Wertgutachten",
    service3Text: "Markt- und Wertermittlung für Immobilien und Grundstücke – getrennt von der technischen Zustandsprüfung.",
    service3Tags: "Marktwert · Grundstück · Entscheidung",
    service4Title: "Technische Kaufberatung",
    service4Text: "Zustand, erkennbare Risiken und zu erwartende Investitionen vor dem Immobilienkauf einordnen.",
    service4Tags: "Bestand · Risiken · Folgekosten",
    service5Title: "Bauplanung und Baugenehmigung",
    service5Text: "Planungs- und Genehmigungsunterlagen für Neubau, Umbau, Sanierung und Modernisierung.",
    service5Tags: "Planung · Genehmigung · Modernisierung",
    service6Title: "Ausschreibung, Vergabe und Baubegleitung",
    service6Text: "Leistungsumfang strukturieren, Angebote vergleichen, Fachunternehmen auswählen und die Ausführung bis zur Abnahme begleiten.",
    service6Tags: "Ausschreibung · Vergabe · Abnahme",
    projectsEyebrow: "Erfahrung wird nachvollziehbar, wenn Rolle und Ergebnis sichtbar sind.",
    projectsTitle: "Ausgewählte Projekterfahrung",
    projectsIntro: "Die Arbeitsfassung zeigt, wie bestehende Referenzen von einer Bildergalerie zu belastbaren Fallbeispielen weiterentwickelt werden können.",
    verifiedExisting: "Öffentliches Bestandsprojekt",
    caseTitle: "Mehrfamilienhaus Ollenhauer Straße 35",
    caseSummary: "Von der konzeptionellen Lösung im bestehenden Wohngebiet bis zur schlüsselfertigen Übergabe.",
    caseTaskLabel: "Aufgabe",
    caseTask: "Planung und Bau eines neuen Mehrfamilienhauses",
    caseScopeLabel: "Leistungsbild laut Bestand",
    caseScope: "Genehmigungen, Arbeits- und Ausschreibungsunterlagen, Koordination und Bauüberwachung",
    caseProofLabel: "Vor Veröffentlichung ergänzen",
    caseProof: "Rolle, Projektkennzahlen, Ergebnis, Freigaben und weitere Bildrechte",
    viewSource: "Bestehende Projektquelle öffnen",
    stadeTitle: "Logistikzentrum mit Parkhaus",
    stadeFact1: "10.000 m² Ausbaufläche",
    stadeFact2: "2.800 m² Mezzanine",
    stadeFact3: "ca. 30 Mio. € Bauvolumen¹",
    geisbergTitle: "Geisbergstraße 6",
    geisbergFact1: "120 Wohnungen modernisiert",
    geisbergFact2: "58 neue Apartments",
    geisbergFact3: "38 Mio. € Projektkosten¹",
    projectNote: "¹ Bestandsangaben aus dem aktuellen öffentlichen Projektarchiv; Aufgabenanteile, Zahlen und Nutzungsrechte werden vor Veröffentlichung bestätigt.",
    profileEyebrow: "Wissenschaft · Planung · Ausführung · Bewertung",
    profileTitle: "Fachliche Tiefe statt austauschbarer Versprechen.",
    profileLead: "Der neue Auftritt soll nicht nur Leistungen aufzählen. Er soll erklären, wie Dr.-Ing. D. Sanders technische Risiken einordnet, Entscheidungen vorbereitet und komplexe Vorhaben bis zur Umsetzung begleitet.",
    statusExisting: "Im Bestand vorhanden",
    ledger1Title: "Beruflicher Werdegang",
    ledger1Text: "Tätigkeit seit 1978, Unternehmensgründung 1995, Sachverständigentätigkeit seit 2001.",
    statusCheck: "Zu bestätigen",
    ledger2Title: "Qualifikationen und Status",
    ledger2Text: "Bezeichnungen, Kammerzugehörigkeit, Zertifikate und Versicherungsangaben.",
    statusBuild: "Auszubauen",
    ledger3Title: "Publikationen und Patente",
    ledger3Text: "Auswahl, bibliografische Daten, Relevanz und überprüfbare Verweise.",
    processEyebrow: "Der Weg zum neuen Auftritt",
    processTitle: "Gestalten, ohne das Bestehende zu gefährden.",
    processIntro: "Der neue Webauftritt entsteht getrennt vom laufenden System. Erst nach fachlicher, technischer und inhaltlicher Abnahme wird kontrolliert umgestellt.",
    process1Title: "Verstehen und sichern",
    process1Text: "Ziele, Zielgruppen, Systeme, Zugänge, Abhängigkeiten und wiederherstellbare Backups klären.",
    process2Title: "Struktur und Beweise",
    process2Text: "Leistungen, Kundenfragen, Fälle, Nachweise und Sprachversionen verbindlich ordnen.",
    process3Title: "Auf Staging umsetzen",
    process3Text: "Design, Inhalte, Formulare, Performance, Barrierearmut und technische Grundlagen separat testen.",
    process4Title: "Kontrolliert starten",
    process4Text: "Weiterleitungen, DNS, E-Mail, Analytics, Formulare und Rollback vor dem Umschalten verifizieren.",
    contactEyebrow: "Der nächste Schritt",
    contactTitle: "Zuerst die richtige Aufgabe definieren.",
    contactText: "In einem ersten Gespräch werden Prioritäten, verfügbare Nachweise und der technische Ausgangspunkt geklärt. Danach lassen sich Umfang, Verantwortung und ein belastbarer Umsetzungsweg festlegen.",
    contactDraft: "Kontaktweg im Konzept – keine Formulardaten werden gespeichert",
    footerSub: "Ingenieurbüro · Immobilien und Bauprojekte",
    footerDraft: "Arbeitsfassung 01 · zur gemeinsamen Abstimmung · nicht zur Veröffentlichung",
    backTop: "Nach oben ↑"
  },
  ru: {
    skip: "Перейти к содержанию",
    draftLabel: "Рабочая концепция",
    draftText: "Не для публикации · содержание и доказательства проверяются совместно",
    brandSub: "Инженерное бюро · недвижимость и строительство",
    menu: "Меню",
    navPaths: "Ваш проект",
    navServices: "Услуги",
    navProjects: "Проекты",
    navProfile: "Профиль",
    navProcess: "Подход",
    navContact: "Контакт",
    heroEyebrow: "Берлин · Тельтов · Бранденбург",
    heroTitle: "Комплексные инженерные услуги для недвижимости и строительства.",
    heroLead: "Техническая проверка, оценка, проектирование и руководство строительством — отдельно или как согласованный путь до передачи объекта.",
    heroScope: "Мы проверяем, проектируем, координируем и контролируем. Строительные работы выполняют привлечённые специализированные компании.",
    heroCta: "Обсудить проект",
    heroSecondary: "Избранные проекты",
    proofSince: "начало работы в строительстве¹",
    proofPubs: "научных работ¹",
    proofPatents: "патента в области стройматериалов¹",
    proofNote: "¹ Данные действующего сайта; подтверждения и формулировки проверяются до публикации.",
    heroCaption: "Реконструкция, модернизация и новое строительство",
    pathsEyebrow: "Один контакт · отдельные модули или согласованный комплекс",
    pathsTitle: "Какой проект вы хотите решить безопасно?",
    pathsIntro: "Начинаем с вашей ситуации, а не с непонятного перечня технических дисциплин.",
    path1Title: "Купить или продать недвижимость",
    path1Text: "Раздельно и понятно проверить техническое состояние, риски, будущие расходы и рыночную стоимость.",
    path2Title: "Проверить, реконструировать или перестроить объект",
    path2Text: "Установить повреждения и причины, спланировать меры и профессионально сопровождать выполнение.",
    path3Title: "Новое строительство — от проектирования до передачи",
    path3Text: "Разрешение, тендер, выбор подрядчиков, руководство строительством, контроль качества и приёмка как единый процесс.",
    servicesEyebrow: "В порядке реальной ценности для бизнеса и вопросов клиентов",
    servicesTitle: "Услуги — отдельно или в разумной комбинации.",
    service1Title: "Руководство строительством",
    service1Text: "Координация специализированных компаний, сроков, качества и решений до организованной передачи объекта.",
    service1Tags: "Координация · Сроки · Качество",
    service2Title: "Строительная экспертиза и оценка повреждений",
    service2Text: "Техническое обследование дефектов, повреждений и причин с понятной документацией.",
    service2Tags: "Балкон · Крыша · Подвал · Приёмка",
    service3Title: "Оценка недвижимости и стоимости",
    service3Text: "Определение рыночной стоимости недвижимости и участков отдельно от технического обследования состояния.",
    service3Tags: "Рыночная стоимость · Участок · Решение",
    service4Title: "Техническая консультация перед покупкой",
    service4Text: "Оценка состояния, видимых рисков и будущих вложений до покупки недвижимости.",
    service4Tags: "Состояние · Риски · Будущие расходы",
    service5Title: "Проектирование и разрешение на строительство",
    service5Text: "Проектные и разрешительные документы для нового строительства, перестройки, реконструкции и модернизации.",
    service5Tags: "Проектирование · Разрешение · Модернизация",
    service6Title: "Тендер, выбор подрядчиков и сопровождение",
    service6Text: "Определение объёма, сравнение предложений, выбор специализированных компаний и сопровождение до приёмки.",
    service6Tags: "Тендер · Выбор · Приёмка",
    projectsEyebrow: "Опыт становится убедительным, когда видны роль и результат.",
    projectsTitle: "Избранный проектный опыт",
    projectsIntro: "Рабочая версия показывает, как превратить существующую галерею в проверяемые кейсы с задачей, вкладом и результатом.",
    verifiedExisting: "Опубликованный проект",
    caseTitle: "Жилой дом, Ollenhauer Straße 35",
    caseSummary: "От концепции в существующей жилой застройке до передачи объекта под ключ.",
    caseTaskLabel: "Задача",
    caseTask: "Проектирование и строительство нового многоквартирного дома",
    caseScopeLabel: "Объём по действующему сайту",
    caseScope: "Разрешения, рабочая и тендерная документация, координация и строительный надзор",
    caseProofLabel: "Дополнить до публикации",
    caseProof: "Роль, показатели проекта, результат, разрешения и права на изображения",
    viewSource: "Открыть текущую страницу проекта",
    stadeTitle: "Логистический центр с паркингом",
    stadeFact1: "10 000 м² отделочных работ",
    stadeFact2: "2 800 м² мезонина",
    stadeFact3: "около 30 млн евро объёма¹",
    geisbergTitle: "Geisbergstraße 6",
    geisbergFact1: "модернизировано 120 квартир",
    geisbergFact2: "58 новых апартаментов",
    geisbergFact3: "38 млн евро стоимости проекта¹",
    projectNote: "¹ Данные действующего публичного архива; вклад, цифры и права использования подтверждаются до публикации.",
    profileEyebrow: "Наука · проектирование · реализация · оценка",
    profileTitle: "Профессиональная глубина вместо взаимозаменяемых обещаний.",
    profileLead: "Новый сайт должен не просто перечислять услуги. Он должен показать, как Dr.-Ing. D. Sanders оценивает технические риски, готовит решения и сопровождает сложные проекты до реализации.",
    statusExisting: "Есть на сайте",
    ledger1Title: "Профессиональный путь",
    ledger1Text: "Работа с 1978 года, основание компании в 1995 году, экспертная деятельность с 2001 года.",
    statusCheck: "Нужно подтвердить",
    ledger2Title: "Квалификации и статус",
    ledger2Text: "Профессиональные обозначения, палаты, сертификаты и сведения о страховании.",
    statusBuild: "Нужно развить",
    ledger3Title: "Публикации и патенты",
    ledger3Text: "Отбор, библиографические данные, значимость и проверяемые ссылки.",
    processEyebrow: "Путь к новому сайту",
    processTitle: "Создавать новое, не подвергая риску существующее.",
    processIntro: "Новый сайт создаётся отдельно от работающей системы. Переключение происходит только после профессиональной, технической и содержательной приёмки.",
    process1Title: "Понять и защитить",
    process1Text: "Уточнить цели, аудитории, системы, доступы, зависимости и проверяемые резервные копии.",
    process2Title: "Структура и доказательства",
    process2Text: "Согласовать услуги, вопросы клиентов, кейсы, подтверждения и языковые версии.",
    process3Title: "Реализовать на staging",
    process3Text: "Отдельно проверить дизайн, контент, формы, скорость, доступность и техническую основу.",
    process4Title: "Запустить контролируемо",
    process4Text: "До переключения проверить редиректы, DNS, почту, аналитику, формы и возможность отката.",
    contactEyebrow: "Следующий шаг",
    contactTitle: "Сначала правильно определить задачу.",
    contactText: "На первой встрече уточняются приоритеты, доступные доказательства и техническая исходная точка. После этого можно определить объём, ответственность и надёжный путь реализации.",
    contactDraft: "Контактный блок концепции — данные форм не сохраняются",
    footerSub: "Инженерное бюро · недвижимость и строительство",
    footerDraft: "Рабочая версия 01 · для совместного обсуждения · не для публикации",
    backTop: "Наверх ↑"
  },
  en: {
    skip: "Skip to content",
    draftLabel: "Working concept",
    draftText: "Not for publication · content and evidence will be reviewed together",
    brandSub: "Engineering office · real estate and construction",
    menu: "Menu",
    navPaths: "Your project",
    navServices: "Services",
    navProjects: "Projects",
    navProfile: "Profile",
    navProcess: "Process",
    navContact: "Contact",
    heroEyebrow: "Berlin · Teltow · Brandenburg",
    heroTitle: "Integrated engineering services for real estate and construction.",
    heroLead: "Technical inspection, valuation, planning and construction management — individually or as a coordinated path through handover.",
    heroScope: "We inspect, plan, coordinate and supervise. Construction work is carried out by appointed specialist contractors.",
    heroCta: "Discuss a project",
    heroSecondary: "Selected projects",
    proofSince: "start of construction practice¹",
    proofPubs: "scientific publications¹",
    proofPatents: "patents in building materials¹",
    proofNote: "¹ Claims from the existing website; evidence and wording will be confirmed before publication.",
    heroCaption: "Refurbishment, modernisation and new construction",
    pathsEyebrow: "One point of contact · individual modules or a coordinated package",
    pathsTitle: "Which project decision do you want to make safely?",
    pathsIntro: "The starting point is your situation, not a confusing catalogue of technical disciplines.",
    path1Title: "Buy or sell a property",
    path1Text: "Review technical condition, visible risks, follow-on costs and market value separately and transparently.",
    path2Title: "Inspect, refurbish or alter an existing property",
    path2Text: "Clarify damage and causes, plan measures and provide professional support during execution.",
    path3Title: "Build new – from planning through handover",
    path3Text: "Permits, tendering, contractor selection, construction management, quality control and acceptance as one coordinated process.",
    servicesEyebrow: "Ordered by business value and real client questions",
    servicesTitle: "Services — available individually or in a sensible combination.",
    service1Title: "Construction management",
    service1Text: "Coordination of specialist contractors, schedules, quality and decisions through an orderly handover.",
    service1Tags: "Coordination · Schedules · Quality",
    service2Title: "Building and damage assessment",
    service2Text: "Technical investigation of defects, damage and causes with traceable documentation.",
    service2Tags: "Balcony · Roof · Basement · Acceptance",
    service3Title: "Property valuation",
    service3Text: "Market and value assessment for properties and land, clearly separated from technical condition inspection.",
    service3Tags: "Market value · Land · Decision",
    service4Title: "Technical purchase advice",
    service4Text: "Assessment of condition, visible risks and expected investment before a property purchase.",
    service4Tags: "Condition · Risks · Follow-on costs",
    service5Title: "Planning and building permits",
    service5Text: "Planning and permit documentation for new construction, alteration, refurbishment and modernisation.",
    service5Tags: "Planning · Permits · Modernisation",
    service6Title: "Tendering, award and construction support",
    service6Text: "Structure scope, compare bids, select specialist contractors and support delivery through acceptance.",
    service6Tags: "Tendering · Award · Acceptance",
    projectsEyebrow: "Experience becomes credible when role and outcome are visible.",
    projectsTitle: "Selected project experience",
    projectsIntro: "This working draft shows how existing references can evolve from an image gallery into evidence-led case studies.",
    verifiedExisting: "Existing public project",
    caseTitle: "Residential building, Ollenhauer Straße 35",
    caseSummary: "From a concept within an existing residential area through to turnkey handover.",
    caseTaskLabel: "Task",
    caseTask: "Planning and construction of a new apartment building",
    caseScopeLabel: "Scope stated on the existing site",
    caseScope: "Permits, working and tender documents, coordination and construction supervision",
    caseProofLabel: "Complete before publication",
    caseProof: "Role, project metrics, outcome, approvals and additional image rights",
    viewSource: "Open existing project source",
    stadeTitle: "Logistics centre with parking structure",
    stadeFact1: "10,000 m² fit-out area",
    stadeFact2: "2,800 m² mezzanine",
    stadeFact3: "approx. €30m construction volume¹",
    geisbergTitle: "Geisbergstraße 6",
    geisbergFact1: "120 apartments modernised",
    geisbergFact2: "58 new apartments",
    geisbergFact3: "€38m project cost¹",
    projectNote: "¹ Existing public project archive data; responsibilities, figures and usage rights will be confirmed before publication.",
    profileEyebrow: "Research · planning · delivery · valuation",
    profileTitle: "Professional depth instead of interchangeable promises.",
    profileLead: "The new presence should do more than list services. It should explain how Dr.-Ing. D. Sanders assesses technical risk, prepares decisions and guides complex projects through delivery.",
    statusExisting: "On the existing site",
    ledger1Title: "Professional background",
    ledger1Text: "Construction practice since 1978, company founded in 1995, expert practice since 2001.",
    statusCheck: "To be confirmed",
    ledger2Title: "Qualifications and status",
    ledger2Text: "Professional titles, chamber membership, certificates and insurance information.",
    statusBuild: "To be developed",
    ledger3Title: "Publications and patents",
    ledger3Text: "Selection, bibliographic data, relevance and verifiable references.",
    processEyebrow: "The path to the new website",
    processTitle: "Build the new without putting the existing at risk.",
    processIntro: "The new presence is developed separately from the live system. Migration happens only after professional, technical and content acceptance.",
    process1Title: "Understand and protect",
    process1Text: "Clarify goals, audiences, systems, access, dependencies and restorable backups.",
    process2Title: "Structure and evidence",
    process2Text: "Agree services, client questions, cases, evidence and language versions.",
    process3Title: "Build on staging",
    process3Text: "Test design, content, forms, performance, accessibility and technical foundations separately.",
    process4Title: "Launch under control",
    process4Text: "Verify redirects, DNS, email, analytics, forms and rollback before switching over.",
    contactEyebrow: "The next step",
    contactTitle: "Define the right task first.",
    contactText: "An initial discussion clarifies priorities, available evidence and the technical starting point. Scope, responsibility and a robust delivery path can then be defined.",
    contactDraft: "Concept contact route — no form data is stored",
    footerSub: "Engineering office · real estate and construction",
    footerDraft: "Working version 01 · for joint review · not for publication",
    backTop: "Back to top ↑"
  }
};

const languageButtons = [...document.querySelectorAll("[data-lang]")];
const translatable = [...document.querySelectorAll("[data-i18n]")];

function setLanguage(language) {
  const dictionary = translations[language] || translations.de;
  document.documentElement.lang = language;
  translatable.forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) element.textContent = dictionary[key];
  });
  languageButtons.forEach((button) => {
    const active = button.dataset.lang === language;
    button.classList.toggle("is-active", active);
    button.setAttribute("aria-pressed", String(active));
  });
  try { localStorage.setItem("dr-sanders-concept-language", language); } catch (_) {}
}

languageButtons.forEach((button) => button.addEventListener("click", () => setLanguage(button.dataset.lang)));

const menuToggle = document.querySelector("[data-menu-toggle]");
const nav = document.querySelector("[data-nav]");

function closeMenu() {
  nav?.classList.remove("is-open");
  menuToggle?.setAttribute("aria-expanded", "false");
}

menuToggle?.addEventListener("click", () => {
  const open = !nav.classList.contains("is-open");
  nav.classList.toggle("is-open", open);
  menuToggle.setAttribute("aria-expanded", String(open));
});

nav?.querySelectorAll("a").forEach((link) => link.addEventListener("click", closeMenu));
window.addEventListener("resize", () => { if (window.innerWidth > 1120) closeMenu(); });

let savedLanguage = "de";
try { savedLanguage = localStorage.getItem("dr-sanders-concept-language") || "de"; } catch (_) {}
const requestedLanguage = new URLSearchParams(window.location.search).get("lang");
if (requestedLanguage && translations[requestedLanguage]) savedLanguage = requestedLanguage;
setLanguage(savedLanguage);

// Make direct links to sections deterministic after images and sticky-header layout settle.
window.addEventListener("load", () => {
  if (!window.location.hash) return;
  const target = document.querySelector(window.location.hash);
  if (!target) return;
  const previousBehavior = document.documentElement.style.scrollBehavior;
  document.documentElement.style.scrollBehavior = "auto";
  target.scrollIntoView({ block: "start" });
  requestAnimationFrame(() => { document.documentElement.style.scrollBehavior = previousBehavior; });
});
