const translations = {
  de: {
    skip: "Zum Inhalt springen",
    draftLabel: "Arbeitskonzept",
    draftText: "Öffentlich einsehbarer Entwurf · noch nicht als Produktionswebsite freigegeben",
    themeLabel: "Farbvariante",
    themeSteel: "Stahlblau",
    themeGreen: "Graphitgrün",
    brandSub: "Ingenieurbüro · Immobilien und Bauprojekte",
    menu: "Menü",
    navPaths: "Ihr Problem",
    navServices: "Leistungen",
    navProjects: "Projekte",
    navProfile: "Profil",
    navProcess: "Vorgehen",
    navContact: "Kontakt",
    heroEyebrow: "Technische Expertise · Berlin · Teltow · Brandenburg",
    heroTitle: "Technische Expertise für Immobilien und Bauprojekte.",
    heroLead: "Schäden erkennen, Werte beurteilen, Bauvorhaben planen und die Ausführung fachlich begleiten.",
    heroScope: "Wir prüfen, planen, koordinieren und überwachen. Die Bauausführung erfolgt durch beauftragte Fachunternehmen.",
    heroCta: "Anliegen besprechen",
    heroSecondary: "Eigenes Problem finden",
    stampExisting: "BESTAND",
    stampPlanning: "PLANUNG",
    stampSupport: "BEGLEITUNG",
    imageLabel: "ARBEITSBILD",
    heroImageAlt: "Arbeitsbild eines mehrgeschossigen Wohn- und Bestandsprojekts",
    heroProject: "Arbeitsbild für den Konzeptentwurf",
    heroCaption: "Projektzuordnung und Bildrechte vor Produktion zu bestätigen",
    pathsEyebrow: "Ein Ansprechpartner · einzelne Module oder abgestimmtes Gesamtpaket",
    pathsTitle: "Welches Vorhaben möchten Sie sicher entscheiden?",
    pathsIntro: "Der Einstieg folgt Ihrer Situation – nicht einer unübersichtlichen Liste technischer Gewerke.",
    path1Title: "Immobilie kaufen oder verkaufen",
    path1Text: "Technischen Zustand, erkennbare Risiken, Folgekosten und Marktwert getrennt und nachvollziehbar prüfen.",
    path2Title: "Bestand prüfen, sanieren oder umbauen",
    path2Text: "Schäden und Ursachen klären, Maßnahmen planen und die Ausführung fachlich begleiten.",
    path3Title: "Neu bauen – von der Planung bis zur Übergabe",
    path3Text: "Genehmigung, Ausschreibung, Vergabe, Bauleitung, Qualitätskontrolle und Abnahme als abgestimmter Prozess.",
    problemsEyebrow: "Der Einstieg folgt Ihrer konkreten Situation",
    problemsTitle: "Welches Problem möchten Sie klären?",
    problemsIntro: "Wählen Sie die Frage, die Ihrem Fall am nächsten kommt. Darunter sehen Sie die passende technische Leistung.",
    problem1Title: "Risse in Wand oder Decke – harmlos oder gefährlich?",
    problem1Service: "Bau- und Schadengutachten",
    problem2Title: "Feuchtigkeit, Schimmel oder eindringendes Wasser – woher kommt es?",
    problem2Service: "Ursachen- und Schadensanalyse",
    problem3Title: "Wie erkenne ich, ob auf meiner Baustelle richtig gearbeitet wird?",
    problem3Service: "Bauleitung und Qualitätskontrolle",
    problem4Title: "Die Bauabnahme steht an – wie übersehe ich keine Mängel?",
    problem4Service: "Abnahmebegleitung",
    problem5Title: "Welche erkennbaren Risiken hat die Immobilie vor dem Kauf?",
    problem5Service: "Technische Kaufberatung",
    problem6Title: "Was ist die Immobilie oder das Grundstück wirklich wert?",
    problem6Service: "Immobilienbewertung und Wertgutachten",
    problem7Title: "Umbau oder Sanierung geplant – was ist sinnvoll und machbar?",
    problem7Service: "Bauplanung und Genehmigung",
    servicesEyebrow: "Nach Geschäftswert und realen Kundenfragen geordnet",
    servicesTitle: "Die Leistungen – einzeln wählbar, sinnvoll kombinierbar.",
    service1Title: "Bauleitung und Qualitätskontrolle",
    service1Text: "Fachunternehmen, Termine und Qualität koordinieren und die Ausführung im vereinbarten Umfang fachlich kontrollieren.",
    service1Tags: "Koordination · Termine · Qualität",
    service2Title: "Bau- und Schadengutachten",
    service2Text: "Technische Untersuchung von Schäden, Mängeln und Ursachen mit nachvollziehbarer Dokumentation.",
    service2Tags: "Balkon · Dach · Keller · Abnahme",
    service3Title: "Immobilienbewertung und Wertgutachten",
    service3Text: "Markt- und Wertermittlung für Immobilien und Grundstücke – getrennt von der technischen Zustandsprüfung.",
    service3Tags: "Marktwert · Grundstück · Entscheidung",
    service4Title: "Technische Kaufberatung",
    service4Text: "Zustand, erkennbare Risiken und zu erwartende Investitionen vor dem Immobilienkauf einordnen.",
    service4Tags: "Bestand · Risiken · Folgekosten",
    service5Title: "Bauplanung und Baugenehmigung",
    service5Text: "Planungs- und Genehmigungsunterlagen für Neubau, Umbau, Sanierung und Modernisierung.",
    service5Tags: "Planung · Genehmigung · Modernisierung",
    service6Title: "Vom Leistungsverzeichnis bis zur Abnahme",
    service6Text: "Leistungsumfang strukturieren, Angebote vergleichen, Fachunternehmen auswählen und die Ausführung bis zur Abnahme begleiten.",
    service6Tags: "Ausschreibung · Vergabe · Abnahme",
    projectsEyebrow: "Erfahrung wird nachvollziehbar, wenn Rolle und Ergebnis sichtbar sind.",
    projectsTitle: "Ausgewählte Projekterfahrung",
    projectsIntro: "Die Arbeitsfassung zeigt, wie bestehende Referenzen von einer Bildergalerie zu belastbaren Fallbeispielen weiterentwickelt werden können.",
    caseStatus: "Beispielstruktur · Projektdaten vor Freigabe",
    caseImageAlt: "Arbeitsbild als Platzhalter für eine spätere Fallstudie",
    caseKicker: "Wohnanlage · Bestand",
    caseTitle: "Schäden an Balkonen und Fassaden technisch einordnen",
    caseSummary: "So kann ein späterer Fall die Ausgangslage, die fachliche Aufgabe und den Nutzen für den Auftraggeber verständlich zeigen.",
    caseTaskLabel: "Ausgangslage",
    caseTask: "Schäden und Sanierungsbedarf an Balkonen und Fassaden einer bestehenden Wohnanlage.",
    caseScopeLabel: "Fachliche Aufgabe",
    caseScope: "Bestand aufnehmen, mögliche Ursachen einordnen, Maßnahmen planen und deren Ausführung – sofern beauftragt – fachlich begleiten.",
    caseProofLabel: "Vor Produktion",
    caseProof: "Konkretes Objekt, Rolle, Ergebnis, Freigaben und Bildrechte werden gemeinsam bestätigt.",
    viewSource: "Bestehende Projektquelle öffnen",
    stadeTitle: "Logistikzentrum mit Parkhaus",
    stadeFact1: "10.000 m² Ausbaufläche",
    stadeFact2: "2.800 m² Mezzanine",
    stadeFact3: "ca. 30 Mio. € Bauvolumen¹",
    geisbergTitle: "Geisbergstraße 6",
    geisbergFact1: "120 Wohnungen modernisiert",
    geisbergFact2: "58 neue Apartments",
    geisbergFact3: "38 Mio. € Projektkosten¹",
    projectNote: "Das Bild stammt aus dem bestehenden öffentlichen Projektarchiv und dient im Arbeitskonzept nur als Platzhalter. Nutzung und Zuordnung werden vor Produktion bestätigt.",
    profileEyebrow: "Warum Dr. Sanders?",
    profileTitle: "Planung, Baupraxis und Begutachtung in einer technischen Logik.",
    profileLead: "Planungs-, Praxis- und Sachverständigenerfahrung ermöglichen es, Ursache, geeignete Maßnahmen und die fachliche Kontrolle der Ausführung in einer zusammenhängenden technischen Logik zu betrachten.",
    statusExisting: "Im Bestand vorhanden",
    ledger1Title: "Ursache und Maßnahmen verbinden",
    ledger1Text: "Die technische Prüfung endet nicht bei der Feststellung: mögliche Ursachen und sinnvolle nächste Maßnahmen werden nachvollziehbar eingeordnet.",
    statusCheck: "Zu bestätigen",
    ledger2Title: "Technik und Marktwert trennen",
    ledger2Text: "Der bauliche Zustand und die wirtschaftliche Bewertung werden als unterschiedliche Fragen transparent behandelt.",
    statusBuild: "Auszubauen",
    ledger3Title: "Fachlich begleiten – nicht selbst ausführen",
    ledger3Text: "Das Büro prüft, plant, koordiniert und überwacht. Beauftragte Fachunternehmen führen die Bauarbeiten aus.",
    profileNote: "Konkrete Nachweise und freigegebene Projektdaten werden erst nach gemeinsamer Prüfung in eine Produktionswebsite übernommen.",
    processEyebrow: "Vom Anliegen zur belastbaren Entscheidung",
    processTitle: "Ein nachvollziehbarer technischer Weg.",
    processIntro: "Der konkrete Ablauf hängt vom Auftrag ab. Das Konzept zeigt die gemeinsame Grundlogik, ohne feste Dauer oder Ergebnisse zu versprechen.",
    process1Title: "Problem und Unterlagen",
    process1Text: "Anliegen, Objekt, vorhandene Pläne, Bilder und bisherige Maßnahmen werden eingeordnet.",
    process2Title: "Technische Untersuchung",
    process2Text: "Je nach Aufgabe folgen Ortsbesichtigung, Bestandsprüfung oder Auswertung der verfügbaren Dokumentation.",
    process3Title: "Einordnung und nächste Maßnahmen",
    process3Text: "Feststellungen, mögliche Ursachen und sinnvolle nächste Maßnahmen werden nachvollziehbar dargestellt.",
    process4Title: "Fachliche Begleitung, wenn beauftragt",
    process4Text: "Wenn vereinbart, werden Planung, Auswahl der Fachunternehmen, Ausführung und Abnahme fachlich begleitet; die Bauausführung übernehmen Fachunternehmen.",
    contactEyebrow: "Der nächste Schritt",
    contactTitle: "Beschreiben Sie kurz Ihr Problem.",
    contactText: "Objekt, Situation und vorhandene Unterlagen bilden den Ausgangspunkt. Danach kann geklärt werden, welche technische Leistung sinnvoll ist.",
    contactDraft: "Kontaktweg im Konzept – keine Formulardaten werden gespeichert",
    footerSub: "Ingenieurbüro · Immobilien und Bauprojekte",
    footerDraft: "Arbeitsfassung 03 · öffentlich einsehbarer Entwurf · nicht als Produktionswebsite freigegeben",
    backTop: "Nach oben ↑"
  },
  ru: {
    skip: "Перейти к содержанию",
    draftLabel: "Рабочая концепция",
    draftText: "Публично доступный эскиз · ещё не утверждён как рабочий сайт",
    themeLabel: "Цветовая версия",
    themeSteel: "Стальной синий",
    themeGreen: "Графитовый зелёный",
    brandSub: "Инженерное бюро · недвижимость и строительство",
    menu: "Меню",
    navPaths: "Ваша проблема",
    navServices: "Услуги",
    navProjects: "Проекты",
    navProfile: "Профиль",
    navProcess: "Подход",
    navContact: "Контакт",
    heroEyebrow: "Техническая экспертиза · Берлин · Тельтов · Бранденбург",
    heroTitle: "Техническая экспертиза недвижимости и строительных проектов.",
    heroLead: "Выявить повреждения, оценить стоимость, спроектировать работы и профессионально сопровождать их выполнение.",
    heroScope: "Мы проверяем, проектируем, координируем и контролируем. Строительные работы выполняют привлечённые специализированные компании.",
    heroCta: "Обсудить задачу",
    heroSecondary: "Найти свою проблему",
    stampExisting: "ОБЪЕКТ",
    stampPlanning: "ПРОЕКТИРОВАНИЕ",
    stampSupport: "СОПРОВОЖДЕНИЕ",
    imageLabel: "РАБОЧЕЕ ИЗОБРАЖЕНИЕ",
    heroImageAlt: "Рабочее изображение многоэтажного жилого объекта",
    heroProject: "Рабочее изображение для эскиза",
    heroCaption: "Соответствие проекту и права на изображение подтверждаются до запуска",
    pathsEyebrow: "Один контакт · отдельные модули или согласованный комплекс",
    pathsTitle: "Какой проект вы хотите решить безопасно?",
    pathsIntro: "Начинаем с вашей ситуации, а не с непонятного перечня технических дисциплин.",
    path1Title: "Купить или продать недвижимость",
    path1Text: "Раздельно и понятно проверить техническое состояние, риски, будущие расходы и рыночную стоимость.",
    path2Title: "Проверить, реконструировать или перестроить объект",
    path2Text: "Установить повреждения и причины, спланировать меры и профессионально сопровождать выполнение.",
    path3Title: "Новое строительство — от проектирования до передачи",
    path3Text: "Разрешение, тендер, выбор подрядчиков, руководство строительством, контроль качества и приёмка как единый процесс.",
    problemsEyebrow: "Начинаем с вашей конкретной ситуации",
    problemsTitle: "Какую проблему нужно решить?",
    problemsIntro: "Выберите наиболее близкий вопрос. Под ним указано подходящее техническое направление.",
    problem1Title: "Трещины в стене или потолке — это безобидно или опасно?",
    problem1Service: "Строительная экспертиза и оценка повреждений",
    problem2Title: "Сырость, плесень или проникающая вода — откуда они появляются?",
    problem2Service: "Анализ причин и повреждений",
    problem3Title: "Как понять, правильно ли выполняются работы на моей стройке?",
    problem3Service: "Руководство строительством и контроль качества",
    problem4Title: "Предстоит приёмка — как не пропустить дефекты?",
    problem4Service: "Сопровождение приёмки",
    problem5Title: "Какие видимые технические риски есть у объекта перед покупкой?",
    problem5Service: "Техническая консультация перед покупкой",
    problem6Title: "Сколько на самом деле стоит недвижимость или участок?",
    problem6Service: "Оценка недвижимости и стоимости",
    problem7Title: "Планируется реконструкция — что разумно и технически возможно?",
    problem7Service: "Проектирование и разрешение",
    servicesEyebrow: "В порядке реальной ценности для бизнеса и вопросов клиентов",
    servicesTitle: "Услуги — отдельно или в разумной комбинации.",
    service1Title: "Руководство строительством и контроль качества",
    service1Text: "Координация специализированных компаний, сроков и качества, а также технический контроль выполнения в согласованном объёме.",
    service1Tags: "Координация · Сроки · Качество",
    service2Title: "Строительная экспертиза и оценка повреждений",
    service2Text: "Техническое обследование дефектов, повреждений и причин с понятной документацией.",
    service2Tags: "Балкон · Крыша · Подвал · Приёмка",
    service3Title: "Оценка недвижимости и стоимости",
    service3Text: "Определение рыночной стоимости недвижимости и участков отдельно от технического обследования состояния.",
    service3Tags: "Рыночная стоимость · Участок · Решение",
    service4Title: "Техническая консультация перед покупкой",
    service4Text: "Оценка состояния, видимых рисков и будущих вложений до покупки недвижимости.",
    service4Tags: "Состояние · Риски · Будущие расходы",
    service5Title: "Проектирование и разрешение на строительство",
    service5Text: "Проектные и разрешительные документы для нового строительства, перестройки, реконструкции и модернизации.",
    service5Tags: "Проектирование · Разрешение · Модернизация",
    service6Title: "От технического задания до приёмки",
    service6Text: "Определение объёма, сравнение предложений, выбор специализированных компаний и сопровождение до приёмки.",
    service6Tags: "Тендер · Выбор · Приёмка",
    projectsEyebrow: "Опыт становится убедительным, когда видны роль и результат.",
    projectsTitle: "Избранный проектный опыт",
    projectsIntro: "Рабочая версия показывает, как превратить существующую галерею в проверяемые кейсы с задачей, вкладом и результатом.",
    caseStatus: "Структура примера · данные проекта до утверждения",
    caseImageAlt: "Рабочее изображение-заполнитель для будущего кейса",
    caseKicker: "Жилой комплекс · существующий объект",
    caseTitle: "Техническая оценка повреждений балконов и фасадов",
    caseSummary: "Так будущий кейс сможет понятно показать исходную ситуацию, профессиональную задачу и пользу для заказчика.",
    caseTaskLabel: "Исходная ситуация",
    caseTask: "Повреждения и необходимость санации балконов и фасадов существующего жилого комплекса.",
    caseScopeLabel: "Профессиональная задача",
    caseScope: "Обследовать объект, определить возможные причины, спланировать меры и, если поручено, профессионально сопровождать их выполнение.",
    caseProofLabel: "До запуска сайта",
    caseProof: "Конкретный объект, роль, результат, разрешения и права на изображения подтверждаются совместно.",
    viewSource: "Открыть текущую страницу проекта",
    stadeTitle: "Логистический центр с паркингом",
    stadeFact1: "10 000 м² отделочных работ",
    stadeFact2: "2 800 м² мезонина",
    stadeFact3: "около 30 млн евро объёма¹",
    geisbergTitle: "Geisbergstraße 6",
    geisbergFact1: "модернизировано 120 квартир",
    geisbergFact2: "58 новых апартаментов",
    geisbergFact3: "38 млн евро стоимости проекта¹",
    projectNote: "Изображение взято из существующего публичного архива и используется в эскизе только как заполнитель. Его использование и соответствие кейсу подтверждаются до запуска сайта.",
    profileEyebrow: "Почему Dr. Sanders?",
    profileTitle: "Проектирование, строительная практика и экспертиза в единой технической логике.",
    profileLead: "Опыт проектирования, строительной практики и экспертизы позволяет рассматривать причину проблемы, подходящие меры и профессиональный контроль исполнения как единую техническую задачу.",
    statusExisting: "Есть на сайте",
    ledger1Title: "Связать причину и необходимые меры",
    ledger1Text: "Техническая проверка не заканчивается фиксацией проблемы: возможные причины и разумные следующие меры объясняются последовательно и понятно.",
    statusCheck: "Нужно подтвердить",
    ledger2Title: "Разделять техническое состояние и рыночную стоимость",
    ledger2Text: "Строительное состояние и экономическая оценка прозрачно рассматриваются как разные вопросы.",
    statusBuild: "Нужно развить",
    ledger3Title: "Профессионально сопровождать, но не выполнять работы",
    ledger3Text: "Бюро проверяет, проектирует, координирует и контролирует. Строительные работы выполняют привлечённые специализированные компании.",
    profileNote: "Конкретные подтверждения и разрешённые данные проектов будут перенесены на рабочий сайт только после совместной проверки.",
    processEyebrow: "От обращения к обоснованному решению",
    processTitle: "Понятный технический путь.",
    processIntro: "Конкретный процесс зависит от задачи. Эскиз показывает общую логику без обещаний фиксированных сроков или результата.",
    process1Title: "Проблема и документы",
    process1Text: "Уточняются задача, объект, имеющиеся планы, фотографии и уже выполненные меры.",
    process2Title: "Техническое обследование",
    process2Text: "В зависимости от задачи проводится осмотр, проверка объекта или анализ доступной документации.",
    process3Title: "Оценка и следующие меры",
    process3Text: "Наблюдения, возможные причины и разумные следующие меры излагаются понятным образом.",
    process4Title: "Профессиональное сопровождение по поручению",
    process4Text: "Если согласовано, профессионально сопровождаются проектирование, выбор подрядчиков, выполнение и приёмка; строительные работы выполняют специализированные компании.",
    contactEyebrow: "Следующий шаг",
    contactTitle: "Коротко опишите свою проблему.",
    contactText: "Объект, ситуация и имеющиеся документы образуют исходную точку. После этого можно определить подходящую техническую услугу.",
    contactDraft: "Контактный блок концепции — данные форм не сохраняются",
    footerSub: "Инженерное бюро · недвижимость и строительство",
    footerDraft: "Рабочая версия 03 · публично доступный эскиз · не утверждён как рабочий сайт",
    backTop: "Наверх ↑"
  },
  en: {
    skip: "Skip to content",
    draftLabel: "Working concept",
    draftText: "Publicly viewable concept · not yet approved as a production website",
    themeLabel: "Colour option",
    themeSteel: "Steel blue",
    themeGreen: "Graphite green",
    brandSub: "Engineering office · real estate and construction",
    menu: "Menu",
    navPaths: "Your problem",
    navServices: "Services",
    navProjects: "Projects",
    navProfile: "Profile",
    navProcess: "Process",
    navContact: "Contact",
    heroEyebrow: "Technical expertise · Berlin · Teltow · Brandenburg",
    heroTitle: "Technical expertise for property and construction projects.",
    heroLead: "Identify damage, assess value, plan construction work and provide professional support during delivery.",
    heroScope: "We inspect, plan, coordinate and supervise. Construction work is carried out by appointed specialist contractors.",
    heroCta: "Discuss your situation",
    heroSecondary: "Find your problem",
    stampExisting: "EXISTING BUILDING",
    stampPlanning: "PLANNING",
    stampSupport: "SUPPORT",
    imageLabel: "WORKING IMAGE",
    heroImageAlt: "Working image of a multi-storey residential property",
    heroProject: "Working image for the concept draft",
    heroCaption: "Project attribution and image rights to be confirmed before production",
    pathsEyebrow: "One point of contact · individual modules or a coordinated package",
    pathsTitle: "Which project decision do you want to make safely?",
    pathsIntro: "The starting point is your situation, not a confusing catalogue of technical disciplines.",
    path1Title: "Buy or sell a property",
    path1Text: "Review technical condition, visible risks, follow-on costs and market value separately and transparently.",
    path2Title: "Inspect, refurbish or alter an existing property",
    path2Text: "Clarify damage and causes, plan measures and provide professional support during execution.",
    path3Title: "Build new – from planning through handover",
    path3Text: "Permits, tendering, contractor selection, construction management, quality control and acceptance as one coordinated process.",
    problemsEyebrow: "Start with your specific situation",
    problemsTitle: "Which problem do you need to clarify?",
    problemsIntro: "Choose the question closest to your case. The relevant technical service is shown below it.",
    problem1Title: "Cracks in a wall or ceiling — harmless or dangerous?",
    problem1Service: "Building and damage assessment",
    problem2Title: "Moisture, mould or water ingress — where is it coming from?",
    problem2Service: "Cause and damage analysis",
    problem3Title: "How can I tell whether work on my site is being done correctly?",
    problem3Service: "Construction management and quality control",
    problem4Title: "Handover is approaching — how do I avoid missing defects?",
    problem4Service: "Acceptance support",
    problem5Title: "What visible technical risks does the property present before purchase?",
    problem5Service: "Technical purchase advice",
    problem6Title: "What is the property or land actually worth?",
    problem6Service: "Property valuation",
    problem7Title: "Planning an alteration or refurbishment — what is sensible and feasible?",
    problem7Service: "Planning and permits",
    servicesEyebrow: "Ordered by business value and real client questions",
    servicesTitle: "Services — available individually or in a sensible combination.",
    service1Title: "Construction management and quality control",
    service1Text: "Coordinate specialist contractors, schedules and quality, and technically monitor delivery within the agreed scope.",
    service1Tags: "Coordination · Schedules · Quality",
    service2Title: "Building and damage assessment",
    service2Text: "Technical investigation of defects, damage and causes with traceable documentation.",
    service2Tags: "Balcony · Roof · Basement · Acceptance",
    service3Title: "Property valuation",
    service3Text: "Market and value assessment for properties and land, clearly separated from technical condition inspection.",
    service3Tags: "Market value · Land · Decision",
    service4Title: "Technical purchase advice",
    service4Text: "Assessment of condition, visible risks and expected investment before a property purchase.",
    service4Tags: "Condition · Risks · Follow-on costs",
    service5Title: "Planning and building permits",
    service5Text: "Planning and permit documentation for new construction, alteration, refurbishment and modernisation.",
    service5Tags: "Planning · Permits · Modernisation",
    service6Title: "From specification to acceptance",
    service6Text: "Structure scope, compare bids, select specialist contractors and support delivery through acceptance.",
    service6Tags: "Tendering · Award · Acceptance",
    projectsEyebrow: "Experience becomes credible when role and outcome are visible.",
    projectsTitle: "Selected project experience",
    projectsIntro: "This working draft shows how existing references can evolve from an image gallery into evidence-led case studies.",
    caseStatus: "Example structure · project data pending approval",
    caseImageAlt: "Working-image placeholder for a future case study",
    caseKicker: "Residential complex · existing property",
    caseTitle: "Technical assessment of damage to balconies and façades",
    caseSummary: "A future case study can use this structure to explain the initial situation, professional task and client benefit clearly.",
    caseTaskLabel: "Initial situation",
    caseTask: "Damage and refurbishment needs affecting balconies and façades of an existing residential complex.",
    caseScopeLabel: "Professional task",
    caseScope: "Inspect the property, assess possible causes, plan measures and, when commissioned, provide professional support during delivery.",
    caseProofLabel: "Before production",
    caseProof: "The specific property, role, outcome, approvals and image rights will be confirmed together.",
    viewSource: "Open existing project source",
    stadeTitle: "Logistics centre with parking structure",
    stadeFact1: "10,000 m² fit-out area",
    stadeFact2: "2,800 m² mezzanine",
    stadeFact3: "approx. €30m construction volume¹",
    geisbergTitle: "Geisbergstraße 6",
    geisbergFact1: "120 apartments modernised",
    geisbergFact2: "58 new apartments",
    geisbergFact3: "€38m project cost¹",
    projectNote: "The image comes from the existing public project archive and is used only as a placeholder in this concept. Its use and case attribution will be confirmed before production.",
    profileEyebrow: "Why Dr. Sanders?",
    profileTitle: "Planning, construction practice and assessment in one technical logic.",
    profileLead: "Experience in planning, construction practice and expert assessment makes it possible to consider the cause, suitable measures and professional supervision of delivery as one connected technical task.",
    statusExisting: "On the existing site",
    ledger1Title: "Connect causes with appropriate measures",
    ledger1Text: "Technical inspection does not stop at recording a problem: possible causes and sensible next measures are explained in a traceable sequence.",
    statusCheck: "To be confirmed",
    ledger2Title: "Separate condition from market value",
    ledger2Text: "The building's technical condition and its economic valuation are treated transparently as different questions.",
    statusBuild: "To be developed",
    ledger3Title: "Provide professional support — not construction work",
    ledger3Text: "The office inspects, plans, coordinates and supervises. Appointed specialist contractors carry out the construction work.",
    profileNote: "Specific evidence and approved project details will be added to a production website only after joint review.",
    processEyebrow: "From concern to a robust decision",
    processTitle: "A traceable technical path.",
    processIntro: "The exact process depends on the assignment. This concept shows the shared logic without promising fixed durations or outcomes.",
    process1Title: "Problem and documents",
    process1Text: "The concern, property, available plans, photographs and previous measures are reviewed.",
    process2Title: "Technical investigation",
    process2Text: "Depending on the task, this may involve a site visit, condition inspection or evaluation of available documentation.",
    process3Title: "Assessment and next measures",
    process3Text: "Findings, possible causes and sensible next measures are presented in a traceable way.",
    process4Title: "Professional support when commissioned",
    process4Text: "When agreed, planning, contractor selection, delivery and acceptance are supported professionally; construction work is carried out by specialist contractors.",
    contactEyebrow: "The next step",
    contactTitle: "Briefly describe your problem.",
    contactText: "The property, situation and available documents form the starting point. The appropriate technical service can then be identified.",
    contactDraft: "Concept contact route — no form data is stored",
    footerSub: "Engineering office · real estate and construction",
    footerDraft: "Working version 03 · publicly viewable concept · not approved as a production website",
    backTop: "Back to top ↑"
  }
};

const languageButtons = [...document.querySelectorAll("[data-lang]")];
const translatable = [...document.querySelectorAll("[data-i18n]")];

function setLanguage(language) {
  const dictionary = translations[language] || translations.de;
  document.documentElement.lang = language;
  translatable.forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) element.textContent = dictionary[key];
  });
  document.querySelectorAll("[data-i18n-alt]").forEach((element) => {
    const key = element.dataset.i18nAlt;
    if (dictionary[key]) element.setAttribute("alt", dictionary[key]);
  });
  languageButtons.forEach((button) => {
    const active = button.dataset.lang === language;
    button.classList.toggle("is-active", active);
    button.setAttribute("aria-pressed", String(active));
  });
  try { localStorage.setItem("dr-sanders-concept-language", language); } catch (_) {}
}

languageButtons.forEach((button) => button.addEventListener("click", () => setLanguage(button.dataset.lang)));

const themeButtons = [...document.querySelectorAll("[data-theme-choice]")];

function setTheme(theme) {
  const selected = theme === "green" ? "green" : "steel";
  document.documentElement.dataset.theme = selected;
  themeButtons.forEach((button) => {
    const active = button.dataset.themeChoice === selected;
    button.classList.toggle("is-active", active);
    button.setAttribute("aria-pressed", String(active));
  });
  try { localStorage.setItem("dr-sanders-concept-theme", selected); } catch (_) {}
}

themeButtons.forEach((button) => button.addEventListener("click", () => setTheme(button.dataset.themeChoice)));

const menuToggle = document.querySelector("[data-menu-toggle]");
const nav = document.querySelector("[data-nav]");

function closeMenu() {
  nav?.classList.remove("is-open");
  menuToggle?.setAttribute("aria-expanded", "false");
}

menuToggle?.addEventListener("click", () => {
  const open = !nav.classList.contains("is-open");
  nav.classList.toggle("is-open", open);
  menuToggle.setAttribute("aria-expanded", String(open));
});

nav?.querySelectorAll("a").forEach((link) => link.addEventListener("click", closeMenu));
window.addEventListener("resize", () => { if (window.innerWidth > 1120) closeMenu(); });

let savedLanguage = "de";
try { savedLanguage = localStorage.getItem("dr-sanders-concept-language") || "de"; } catch (_) {}
const requestedLanguage = new URLSearchParams(window.location.search).get("lang");
if (requestedLanguage && translations[requestedLanguage]) savedLanguage = requestedLanguage;
setLanguage(savedLanguage);

let savedTheme = "steel";
try { savedTheme = localStorage.getItem("dr-sanders-concept-theme") || "steel"; } catch (_) {}
const requestedTheme = new URLSearchParams(window.location.search).get("theme");
if (["steel", "green"].includes(requestedTheme)) savedTheme = requestedTheme;
setTheme(savedTheme);

// Make direct links to sections deterministic after images and sticky-header layout settle.
window.addEventListener("load", () => {
  if (!window.location.hash) return;
  const target = document.querySelector(window.location.hash);
  if (!target) return;
  const previousBehavior = document.documentElement.style.scrollBehavior;
  document.documentElement.style.scrollBehavior = "auto";
  target.scrollIntoView({ block: "start" });
  requestAnimationFrame(() => { document.documentElement.style.scrollBehavior = previousBehavior; });
});
